name: Trigger Repo B Workflow

on:
  push:
    branches:
      - main  # This triggers the workflow on push to the main branch

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger streamlit-main Workflow
        run: |
          curl -X POST \
                -H "Accept: application/vnd.github.v3+json" \
               -H "Authorization: token ${{ secrets.REPO_B_PAT }}" \
                https://api.github.com/repos/saurabhdsh/streamlit-main/actions/workflows/ci.yml/dispatches \
               -d '{"ref":"main"}'
      - name: Node Path 
        run: which node 
